In [1]:
# Let's take the example of the nested conditional statement for loop
northeast = ['New York','New Jersey', 'Massachusettes','Vermont','New Hampshire','Maine',
             'Rhode Island','Connecticut','Pennsylvania']
for i in northeast:
    if i.startswith('N'):
        print('A state that start with N')
    elif i.startswith('M'):
        print('A state that start with M')
    else: 
        print('A state that starts with something else')

A state that start with N
A state that start with N
A state that start with M
A state that starts with something else
A state that start with N
A state that start with M
A state that starts with something else
A state that starts with something else
A state that starts with something else


In [2]:
#print state that starts with N otherwise choose a state that starts with M

In [3]:
# What if I want to add up the number of states in each of these categories?
# We can create variables that if the condition is met, it will add one and 
#do this iteratively until the end of the end of the list

nstates = 0
mstates =0 
otherstates= 0

northeast = ['New York','New Jersey', 'Massachusettes','Vermont','New Hampshire',
             'Maine','Rhode Island','Connecticut','Pennsylvania']
for i in northeast:
    if i.startswith('N'):
        nstates = nstates+1
    elif i.startswith('M'):
        mstates = mstates+1
    else: 
        otherstates = otherstates+1

In [4]:
print(nstates)
print(mstates)
print(otherstates)

3
2
4


In [10]:
(nstates+mstates)-Total #give the tota; of state with n and m

-4

In [11]:
len(northeast) #give the total

9

In [14]:
# How do I figure out the total number of items in the list?
total = len(northeast) # length is a function that can tell me how many element are in a list
fraction_nstates = nstates/total
fraction_mstates = mstates/total
fraction_otherstates = otherstates/total

#How can I simplify this code?

In [13]:
#create new data point in this new l
# we can create a for loop out of this and save the information into a list.

total = len(northeast)
ne_statnames = [nstates, mstates, otherstates]  # create a list of items (our variables)
fraction=[] #initialize a list that is empty (contains no items), and name it fraction

for i in ne_statnames: 
    a = i/total # assign a variable a to be the fraction of the item divided by the total
    #(the item is the number if states in that category and total is number of elements in the list that we defined earlier)
    print(a)
    fraction.append(a) #for the list called fraction, append the value a in the list
fraction    

#this loop will calculate the fraction of states in the list and the append that number to a list called fraction 
# it will do this until the end of the list is reached

0.3333333333333333
0.2222222222222222
0.4444444444444444


[0.3333333333333333, 0.2222222222222222, 0.4444444444444444]

In [16]:
# You must initialize the list by creating a variable with an empty list
fraction=[]  # It's empty
type(fraction) #and you can see here this is a list

#tell what's inside the item

list

In [17]:
##APPEND

In [18]:
list1 = [3,9,15]
new_list = [] # create an empty list

for i in list1: # for each item in this list
    k = i*3 #multiple it by 3 and save it as the variable k
    new_list.append(k) # add the variable k to the list called new_list
new_list

[9, 27, 45]

In [19]:
##NESTED LOOPS
#A loop within a loop. What it will do is loop through
#the first set and then the second set in that order.

In [21]:
for i in range(1,5):
    print('outer loop item'+str(i))
    for j in range(6,9):
        print('inner loop item'+str(i))

outer loop item1
inner loop item1
inner loop item1
inner loop item1
outer loop item2
inner loop item2
inner loop item2
inner loop item2
outer loop item3
inner loop item3
inner loop item3
inner loop item3
outer loop item4
inner loop item4
inner loop item4
inner loop item4


In [22]:
# Let's take the example of the nested conditional statement for loop
northeast = ['New York','New Jersey', 'Massachusettes','Vermont','New Hampshire',
             'Maine','Rhode Island','Connecticut','Pennsylvania']
newengland = ['Massachusettes','Vermont','New Hampshire','Maine','Rhode Island']
tot_states_ne = 0

for i in northeast:  # In this loop look at the first item and;
    print(i) # print the value i #first look at this item and tell what it is
    if i in newengland: #look howmany states is in that newengland list 
        # then evaluate if the item i is in the list new england
        #6 new england state
        
        print(i, 'is in new england') # if that's true, print this statement
        tot_states_ne = tot_states_ne+1 # and add 1 to the variable tot_state_ne; 
#         move onto the next item in the list new england until there are no more items, 
# then go to the next item in the list northest
tot_states_ne

New York
New Jersey
Massachusettes
Massachusettes is in new england
Vermont
Vermont is in new england
New Hampshire
New Hampshire is in new england
Maine
Maine is in new england
Rhode Island
Rhode Island is in new england
Connecticut
Pennsylvania


5

In [23]:
# Adding 1 that initalizes at 0 is very useful to help you count 
# The total cout at the end of this for loop will show you how many iterations it took to complete the for loop
counter = 0
for i in northeast:
    
    if i in newengland:
        print(i, 'is in new england')
    
    counter = counter+1
counter


Massachusettes is in new england
Vermont is in new england
New Hampshire is in new england
Maine is in new england
Rhode Island is in new england


9

In [24]:
# Another way to have a counter is to use an addition assignment +=
## += can be very useful to continually add one to a variable. 
# This is often used in counters to help you keep track of the number of iterations that you
# This is equivalent to i = i+1

In [25]:
counter = 0
for i in northeast:
    
    if i in newengland:
        print(i, 'is in new england')
    
    counter +=1
counter

Massachusettes is in new england
Vermont is in new england
New Hampshire is in new england
Maine is in new england
Rhode Island is in new england


9

In [26]:
#The above nested loop will first look at the first item (New York) in the first list (northeast) and then look at all of the items in the second list (newengland) that meets the conditional statement. Then it will go to the second item (New Jersey) in the first list (northeast) and then go through all of the items in the second list (newengland).
#Be careful with nested loops in the logic. Loops will go in order of the loop identified. It will always go to list one and then all the iteams in list two iteratively.

In [27]:
## In line Nested Loops

In [29]:
#To be exactly as stated as before
nelist = [i+str(' is in new england') for i in northeast if i in newengland]

In [35]:
# If I assign i to be a number and add it to a string, you will get an error
i = 7 
i + 'bob'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [31]:
# When I add elements together, I have to make sure it is the same type
i = str(7) #makes i=string 7
i+' bob' #add it as the same type

'7 bob'

In [32]:
i = 7
7+9
#this is the same type

16

In [33]:
# Let's go through another example of nested loops
list1 = [3,9,12] #list of number
x = 0 #initialize list called 0
answers = []

for i in range(5,10): # for each item in the range of numbers 5 through 9 (only go through 5 to 9)
    if (i % 2) == 0: # check to see if i is even (that the remainder of i divided by 2 is equal to 0)
        #, if it is true then do code below; if false, move to next conditional
        x = i*3 #take that i andmultiple i by 3 and save it with the variable x
    else: #otherwise
        for j in list1: # for items (j) that are in list1 and add 5 then,assign that x then apppend it
            x = j+5
    answers.append(x) # append all of these answers from this loop in one list
    
#what happens if answers.append(x) is tabbed inward?
answers

[17, 18, 17, 24, 17]

In [37]:
#Another example
x_list = [10,57,89,76,350,126]
for i in range(25, 350, 25): #going through the list of 25 through 350
    x = i +20
    for j in x_list: #asssign it to the variable x
        if j>100: #if this is true
            x_list = [x-1,j]
        else: 
            x_list2 = [x,j] #[45,10]=[45,57]
            #remain variable

In [38]:
##BREAK

In [39]:
i = [1,2,3,4,5]
i[0:5]

[1, 2, 3, 4, 5]

In [40]:
#while loops will continue until the logical statement that you input is False. 
# In this case, the logical statement is i less than 20.
# The while loop will stop when it hits 20 because 20 is not less than 20 (Thus the last number printed is 19)

i = 1
while i < 20: #stop at 20
    print(i)
    i += 1
    


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [41]:
#In this case, if i is great than 0, the logical statement will always be True 
# The loop will be indefinite
# This is why we must use the break function to tell the loop when to stop.  
# Here, the if condition is used and when that if condition is True it will run the following line
# Which is to stop the loop (break)

i = 1
while i > 0:
    print(i)
    if i == 5:
        break
    i += 1

1
2
3
4
5


In [42]:
# Interest rates on loans example

# suppose you have a loan that starts at 45,832 and the interest rate is 2.75
# here is an example of calculating loans and interest rates with a while loop
i = 45832
y = 0
while i > 0:
    i = i*1.0275
    y += 1
    if y > 15: #if y is greater than 15 break it
        break
print('loan after 15 years of interest', round(i,2))

#note this assumes that you are not paying it off every month. This is the cost of loan without payments
# For an exercise, write a while loop that includes monthly payments of $300

#If I didn't use the break function, this lop would be indefinite because i is always greater than 0 in this loop.

loan after 15 years of interest 70742.12


In [43]:
round?

Signature: round(number, ndigits=None)
Docstring:
Round a number to a given precision in decimal digits.

The return value is an integer if ndigits is omitted or None.  Otherwise
the return value has the same type as the number.  ndigits may be negative.
Type:      builtin_function_or_method


In [44]:
##NUMPY
#Numpy is a package that works with multi-dimesnional arrays 
#to apply mathematical functions and statistics. 
#It does more than this, but that's what we're interested in for this class.

In [45]:
import numpy as np
#I'm calling the book numpy from my library to use in this notebook

In [46]:
# 0 dimensional arrays
np.array(1)

array(1)

In [47]:
# One dimensional arrays
d_1 = np.array([1,4,3,5,8,19])

In [48]:
# 2 dimensional arrays
d_2 = np.array([[1,4,5],[3,5,6],[3,5,6],[3,5,6]])

In [49]:
# 3 dimensional arrays
d_3 = np.array([[[1, 2], [3, 6]], [[1, 6], [9, 8]]])
# <-  the square brackets are very important to determine the dimension

In [50]:
# 0 dimensional arrays
np.array(1)

array(1)

In [67]:
# One dimensional arrays
d_1 = np.array([1,4,3,5,8,19])
d_1

array([ 1,  4,  3,  5,  8, 19])

In [68]:
# 2 dimensional arrays
d_2 = np.array([[1,4,5],[3,5,6],[3,5,6],[3,5,6]])
d_2

array([[1, 4, 5],
       [3, 5, 6],
       [3, 5, 6],
       [3, 5, 6]])

In [69]:
# 3 dimensional arrays
d_3 = np.array([[[1, 2], [3, 6]], [[1, 6], [9, 8]]])
# <-  the square brackets are very important to determine the dimension
d_3

array([[[1, 2],
        [3, 6]],

       [[1, 6],
        [9, 8]]])

In [54]:
##Remember that the format of shape is: (N rows, N columns)

In [55]:
print(d_2.ndim) # The number of dimensions
print(len(d_2)) # number of elements in each dimension
print(d_2.shape) # the shape of the array (N rows, N columns)

2
4
(4, 3)


In [56]:
d_2 = np.array([[-2,5,6],[5,2,7]])
print(d_2.shape)

(2, 3)


In [57]:
# You can turn arrays into matrices as long as it has 2 dimensions
matrix = np.matrix(d_2)
matrix
#define something specifically to be a matrix

matrix([[-2,  5,  6],
        [ 5,  2,  7]])

In [58]:
#example

In [91]:
#let's go back to the interest loan code and create a list of numbers
i = 45832
y = 0
loan = []
while i > 0:
    i = i*1.0275
    y += 1
    loan.append(round(i,2))
    if y > 15:
        break
loan_array = np.array(loan) ## we can assign a new variable that creates an array from a list
loan_array = np.array(loan)

In [92]:
loan

[47092.38,
 48387.42,
 49718.07,
 51085.32,
 52490.17,
 53933.65,
 55416.82,
 56940.79,
 58506.66,
 60115.59,
 61768.77,
 63467.41,
 65212.76,
 67006.11,
 68848.78,
 70742.12]

In [61]:
##use numpy to multiply the two arrays together.

In [62]:
fees = [1.002,1.002,1.003,1.003,1.004,1.005,1.006,1.005,1,1.004,1.001,1.00,1.002,1.003,1.003,1.002]
fees = np.array(fees)

In [63]:
#let's check that both of the arrays are the same dimension and length
print(len(fees),len(loan_array))
print(fees.ndim,loan_array.ndim)

16 16
1 1


In [64]:
fees*loan_array

array([47186.56476, 48484.19484, 49867.22421, 51238.57596, 52700.13068,
       54203.31825, 55749.32092, 57225.49395, 58506.66   , 60356.05236,
       61830.53877, 63467.41   , 65343.18552, 67207.12833, 69055.32634,
       70883.60424])

In [65]:
#see that I have to call np to use the round function when dealing with arrays
total_loan_cost = np.round(fees*loan_array,2)
total_loan_cost

array([47186.56, 48484.19, 49867.22, 51238.58, 52700.13, 54203.32,
       55749.32, 57225.49, 58506.66, 60356.05, 61830.54, 63467.41,
       65343.19, 67207.13, 69055.33, 70883.6 ])

In [66]:
total_loan_cost

array([47186.56, 48484.19, 49867.22, 51238.58, 52700.13, 54203.32,
       55749.32, 57225.49, 58506.66, 60356.05, 61830.54, 63467.41,
       65343.19, 67207.13, 69055.33, 70883.6 ])

In [70]:
#Let's say you have multiple loans with varying fee schedules
#let's go back to the interest loan code and create a list of numbers
##INTEGRATED THAT APPEND
i = 35800
y = 0
loan_2 = []

while i > 0:
    i = i*1.0375
    y += 1
    loan_2.append(round(i,2))
    if y > 15:
        break

In [93]:
#We can create a matrix out of that information
all_loans = np.matrix([loan,loan_2])
all_loans

matrix([[47092.38, 48387.42, 49718.07, 51085.32, 52490.17, 53933.65,
         55416.82, 56940.79, 58506.66, 60115.59, 61768.77, 63467.41,
         65212.76, 67006.11, 68848.78, 70742.12],
        [37142.5 , 38535.34, 39980.42, 41479.68, 43035.17, 44648.99,
         46323.33, 48060.45, 49862.72, 51732.57, 53672.54, 55685.27,
         57773.46, 59939.97, 62187.72, 64519.76]])

In [72]:
# I can change the columns and rows with reshape to the specific shape I want
np.reshape(all_loans,(16,2))

matrix([[47092.38, 48387.42],
        [49718.07, 51085.32],
        [52490.17, 53933.65],
        [55416.82, 56940.79],
        [58506.66, 60115.59],
        [61768.77, 63467.41],
        [65212.76, 67006.11],
        [68848.78, 70742.12],
        [37142.5 , 38535.34],
        [39980.42, 41479.68],
        [43035.17, 44648.99],
        [46323.33, 48060.45],
        [49862.72, 51732.57],
        [53672.54, 55685.27],
        [57773.46, 59939.97],
        [62187.72, 64519.76]])

In [73]:
# transpose is also useful
all_loans = np.transpose(all_loans)# transpose is also useful
all_loans = np.transpose(all_loans)

In [74]:
all_loans_2 = all_loans

In [75]:
##SLICING

In [76]:
#1-d array
total_loan_cost

array([47186.56, 48484.19, 49867.22, 51238.58, 52700.13, 54203.32,
       55749.32, 57225.49, 58506.66, 60356.05, 61830.54, 63467.41,
       65343.19, 67207.13, 69055.33, 70883.6 ])

In [77]:
print(total_loan_cost[5]) #total cost of item 5
total_loan_cost[14:] #last anything after item 14

54203.32


array([69055.33, 70883.6 ])

In [78]:
# Matrix (recall that we created a matrix earlier)
all_loans

matrix([[47092.38, 48387.42, 49718.07, 51085.32, 52490.17, 53933.65,
         55416.82, 56940.79, 58506.66, 60115.59, 61768.77, 63467.41,
         65212.76, 67006.11, 68848.78, 70742.12],
        [37142.5 , 38535.34, 39980.42, 41479.68, 43035.17, 44648.99,
         46323.33, 48060.45, 49862.72, 51732.57, 53672.54, 55685.27,
         57773.46, 59939.97, 62187.72, 64519.76]])

In [79]:
# so, if we want the first row we can call it:
all_loans[0]

matrix([[47092.38, 48387.42, 49718.07, 51085.32, 52490.17, 53933.65,
         55416.82, 56940.79, 58506.66, 60115.59, 61768.77, 63467.41,
         65212.76, 67006.11, 68848.78, 70742.12]])

In [80]:
##Remember from Algebra the matrix locations:

In [81]:
##This works in the same way for index slicing in python (but with 0 indexing)

In [82]:
# If we want all item in the row and give the first column
all_loans[:,0]
# This says, show me all of the rows of the second column.

matrix([[47092.38],
        [37142.5 ]])

In [83]:
# For example:
# If we want the first column with rows 1 through 5
all_loans[0:5,0]
#[rows,0column]
# Here, it will print rows 1 through 5 or, in other words, indexed items at 0 UNTIL 5 (indexed item 1 through 4)

matrix([[47092.38],
        [37142.5 ]])

In [84]:
#How do we get the second column with rows 1 through 3?

In [94]:
all_loans[4:6,3]

matrix([], shape=(0, 1), dtype=float64)

In [95]:
##FILTERING

In [96]:
all_loans[(all_loans > 65000)] #all the ellement in that matrix

matrix([[65212.76, 67006.11, 68848.78, 70742.12]])

In [97]:
all_loans[(all_loans < 40000)]

matrix([[37142.5 , 38535.34, 39980.42]])

In [98]:
all_loans[(all_loans >65000) & (all_loans <67000)] ##SOMETHING BETWEEEN 65000 and 67000

matrix([[65212.76]])

In [99]:
all_loans[(all_loans==65212.76)] #SOMETHING EQUALS TO

matrix([[65212.76]])

In [102]:
# We can use these additional conditionals to replace values in the matrix
# that meet the true condition
all_loans[(all_loans >65000)& (all_loans <67000)] = np.nan
all_loans[(all_loans <38000)] = np.inf

In [101]:
all_loans ##nan is anything missing

matrix([[47092.38, 48387.42, 49718.07, 51085.32, 52490.17, 53933.65,
         55416.82, 56940.79, 58506.66, 60115.59, 61768.77, 63467.41,
              nan, 67006.11, 68848.78, 70742.12],
        [     inf, 38535.34, 39980.42, 41479.68, 43035.17, 44648.99,
         46323.33, 48060.45, 49862.72, 51732.57, 53672.54, 55685.27,
         57773.46, 59939.97, 62187.72, 64519.76]])

In [103]:
##Remember 
#np.isnan() and np.isinf() functions 
#you will use this OFTEN

In [104]:
#let's search for these values
np.isnan(all_loans)
##WHAT IS A LOGICAL FUNCTION

matrix([[False, False, False, False, False, False, False, False, False,
         False, False, False,  True, False, False, False],
        [False, False, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False]])

In [105]:
#we can also filter for only true values from the matrix 
# that are nan by creating a list of all values that are True
all_loans[np.isnan(all_loans)]
#for all the items in loan, give me what is true, Everthing that's not missing

matrix([[nan]])

In [106]:
# Here you can search for a boolean in the matrix to exclude anythign that is a nan
# -> You MUST do the tilda to look exclude nan
# It's kind of like an exclusion boolean. Show me everything but what I asked for.
all_loans[~np.isnan(all_loans)]

matrix([[47092.38, 48387.42, 49718.07, 51085.32, 52490.17, 53933.65,
         55416.82, 56940.79, 58506.66, 60115.59, 61768.77, 63467.41,
         67006.11, 68848.78, 70742.12,      inf, 38535.34, 39980.42,
         41479.68, 43035.17, 44648.99, 46323.33, 48060.45, 49862.72,
         51732.57, 53672.54, 55685.27, 57773.46, 59939.97, 62187.72,
         64519.76]])

In [107]:
all_loans[~np.isinf(all_loans)]

matrix([[47092.38, 48387.42, 49718.07, 51085.32, 52490.17, 53933.65,
         55416.82, 56940.79, 58506.66, 60115.59, 61768.77, 63467.41,
              nan, 67006.11, 68848.78, 70742.12, 38535.34, 39980.42,
         41479.68, 43035.17, 44648.99, 46323.33, 48060.45, 49862.72,
         51732.57, 53672.54, 55685.27, 57773.46, 59939.97, 62187.72,
         64519.76]])

In [108]:
##Python Byte Moment¶

2

In [109]:
# here is an example that I create an array and then I ask it to tell me the dimension of the array
#python will output the last function you ask it to, but it will also calculate everythign prior
np.array([[1,4],[3,5]]).ndim

2

In [110]:
x = np.array([[1,4],[3,5]]).ndim
x

2

In [111]:
x_list =[34,62,35,647,45,29,68,3,55]
x_list = np.array(x_list)

In [112]:
# The above is the same as the code below
x_list = np.array([34,62,35,647,45,29,68,3,55])

In [113]:
##Useful Functions in Numpy

In [114]:
#square root
np.sqrt(loan)

array([217.00778788, 219.97140723, 222.97549193, 226.02061853,
       229.10733292, 232.23619442, 235.40777387, 238.62269381,
       241.88149991, 245.18480785, 248.53323721, 251.92739033,
       255.36789148, 258.85538434, 262.3905105 , 265.97390849])

In [115]:
np.square(loan)

array([2.21769225e+09, 2.34134241e+09, 2.47188648e+09, 2.60970992e+09,
       2.75521795e+09, 2.90883860e+09, 3.07102394e+09, 3.24225357e+09,
       3.42302926e+09, 3.61388416e+09, 3.81538095e+09, 4.02811213e+09,
       4.25270407e+09, 4.48981878e+09, 4.74015451e+09, 5.00444754e+09])

In [116]:
#matrix
np.square(all_loans_2)

matrix([[2.21769225e+09, 2.34134241e+09, 2.47188648e+09, 2.60970992e+09,
         2.75521795e+09, 2.90883860e+09, 3.07102394e+09, 3.24225357e+09,
         3.42302926e+09, 3.61388416e+09, 3.81538095e+09, 4.02811213e+09,
         4.25270407e+09, 4.48981878e+09, 4.74015451e+09, 5.00444754e+09],
        [1.37956531e+09, 1.48497243e+09, 1.59843398e+09, 1.72056385e+09,
         1.85202586e+09, 1.99353231e+09, 2.14585090e+09, 2.30980685e+09,
         2.48629085e+09, 2.67625880e+09, 2.88074155e+09, 3.10084929e+09,
         3.33777268e+09, 3.59280000e+09, 3.86731252e+09, 4.16279943e+09]])

In [117]:
#exponential (also for numbers)
np.exp(2.713)

15.07443104084234

In [118]:
# or an array
np.exp(np.sqrt(loan))

array([1.75907682e+094, 3.40697022e+095, 6.87109168e+096, 1.44380128e+098,
       3.16264505e+099, 7.22599632e+100, 1.72304726e+102, 4.29061135e+103,
       1.11635080e+105, 3.03675039e+106, 8.64198467e+107, 2.57439665e+109,
       8.03278468e+110, 2.62702998e+112, 9.01053989e+113, 3.24340207e+115])

In [119]:
#What's the base of this?
np.log(loan)

array([10.75986648, 10.78699514, 10.81412373, 10.84125246, 10.86838119,
       10.89550987, 10.92263844, 10.94976723, 10.97689587, 11.00402449,
       11.03115318, 11.05828182, 11.08541043, 11.11253909, 11.13966778,
       11.16679643])

In [120]:
np.log10(loan)

array([4.67295064, 4.68473247, 4.69651426, 4.70829612, 4.72007798,
       4.73185981, 4.7436416 , 4.75542349, 4.76720531, 4.77898711,
       4.79076895, 4.80255078, 4.81433258, 4.82611441, 4.83789625,
       4.84967807])

In [121]:
# absolute values
np.abs(loan)

array([47092.38, 48387.42, 49718.07, 51085.32, 52490.17, 53933.65,
       55416.82, 56940.79, 58506.66, 60115.59, 61768.77, 63467.41,
       65212.76, 67006.11, 68848.78, 70742.12])

In [122]:
#round to the nearest integer
# (particularly useful when cleaning data and need to convert to integer)
np.rint(loan)

array([47092., 48387., 49718., 51085., 52490., 53934., 55417., 56941.,
       58507., 60116., 61769., 63467., 65213., 67006., 68849., 70742.])

In [123]:
## Calculations within a Matrix or Array

In [124]:
all_loans[0:1,1]= 57773.46
all_loans[12:13,0] = 37142.5

In [125]:
all_loans

matrix([[47092.38, 57773.46, 49718.07, 51085.32, 52490.17, 53933.65,
         55416.82, 56940.79, 58506.66, 60115.59, 61768.77, 63467.41,
              nan, 67006.11, 68848.78, 70742.12],
        [     inf, 38535.34, 39980.42, 41479.68, 43035.17, 44648.99,
         46323.33, 48060.45, 49862.72, 51732.57, 53672.54, 55685.27,
         57773.46, 59939.97, 62187.72, 64519.76]])

In [126]:
#minimum value of the entire matrix
all_loans.min()

nan

In [127]:
#minimum value for EACH row
all_loans.min(axis=1)

matrix([[     nan],
        [38535.34]])

In [128]:
#minimum value for EACH column
all_loans.min(axis=0)

matrix([[47092.38, 38535.34, 39980.42, 41479.68, 43035.17, 44648.99,
         46323.33, 48060.45, 49862.72, 51732.57, 53672.54, 55685.27,
              nan, 59939.97, 62187.72, 64519.76]])

In [129]:
##Random function

In [130]:
np.random.rand(8,6)

array([[0.08833966, 0.05263721, 0.97422867, 0.48492452, 0.12153708,
        0.03934792],
       [0.5571292 , 0.49326633, 0.94793725, 0.91208767, 0.56082254,
        0.53821316],
       [0.55605673, 0.42163249, 0.68713931, 0.63227691, 0.0251158 ,
        0.12749528],
       [0.17815946, 0.32103941, 0.52386575, 0.79529518, 0.77428586,
        0.07713004],
       [0.61597247, 0.58339142, 0.30560728, 0.71511726, 0.13319148,
        0.5755308 ],
       [0.37596234, 0.06977583, 0.67198747, 0.30109007, 0.66886535,
        0.91958402],
       [0.20668679, 0.63264266, 0.83612821, 0.18265333, 0.42653618,
        0.90713855],
       [0.66516365, 0.73785972, 0.33290843, 0.01212757, 0.31396594,
        0.90503099]])

In [131]:
#in-class activity

In [137]:
# Interest rates on loans example


loan after 12 months of interest 38319.33


In [139]:
i = 45832
y = 0
while i > 0:
    i = (i*1.0275)
    y += 1
    if y > 15:
        break
print('loan after 15 years of interest', round(i,2))

loan after 15 years of interest 76671.32


In [156]:
#Includes annual payment of 12*300
#how many years take to pay of the loan
i = 45832
y = 0
loan = []
while i > 0:
    i = i*1.0275-(12*300)
    y += 1
    loan.append(round(i,2))
    if y > 15:
        break
print('loan after 15 years of interest', round(i,2))

loan after 15 years of interest -408.2
